### ISSUE TITLE
Progression bar resetting when user changes of urls

### ISSUE THREAD

**Issue by xavier-heysch** [rrweb-io/rrweb-player#1]
Hi, I'm using rrweb since a week now and it's really great ! 

I have some troubles for some recorded sessions. 

For some complex sites, when a user switch from a page A to a page B, the progression bar is reset to the start (timer at 0:00). Then, the replay is stuck until the time of the page switch.

Sample example: 
1) Start the replay
2) At 15sec, the user click on a nav menu in the replay
3) The replay progression bar starts again from 0:00 and the "image" is stuck.
4) At 0:15, the replay continues in normal condition.

Have you ever noticed this kind of issue ?

**Comment by Yuyz0112** [comment]
Sounds like a bug, could you provide some reproducible events log for debug usage?

**Comment by xavier-heysch** [comment]
Here an example, I have uploaded the whole session replays (around 2MB of JSON).

Hope you can find something.

[events.json.txt](https://github.com/rrweb-io/rrweb-player/files/3055107/events.json.txt)

It's not the only website where the problem occured but at least you may identify what is wrong :)

**Comment by Yuyz0112** [comment]
@xavier-heysch Thanks for the report! It's a bug and has been fixed in https://github.com/rrweb-io/rrweb/commit/faed623986ade87609212a82098037844fcc3bf9, the latest release of rrweb and rrweb-player should not have this issue anymore.

**Comment by xavier-heysch** [comment]
@Yuyz0112 Thanks for the reactivity ! 
Are rrweb-player and rrweb-record files on jsdelivr.net fixed too ?

**Comment by Yuyz0112** [comment]
@xavier-heysch I think jsdeliver has a cache for the `latest` alias, but you can use the `0.3.10` version which is the latest code now:
https://cdn.jsdelivr.net/npm/rrweb-player@0.3.10/dist/index.js

**Comment by xavier-heysch** [comment]
@Yuyz0112 Everything seems fine. All my records that got the problem can be displayed correctly now. Many thanks !
One more thing, since a full cache clean, it seems that the progression bar of the player is not visible anymore. The progression dot is moving correctly, but the line is not shown.
Do you see this on your side too ?

<img width="1115" alt="Screen Shot 2019-04-09 at 12 08 03" src="https://user-images.githubusercontent.com/7370867/55792155-50f58880-5ac0-11e9-9063-17e6341bd98f.png">

**Comment by Yuyz0112** [comment]
@xavier-heysch There is a style change in this release, but I'm not sure why it causes this issue. https://github.com/rrweb-io/rrweb-player/commit/b200f6b404a5da9897a71d814f9156c15e84dfa6#diff-b346a6c7be3020f6ef10d4a1df6336e8R264

Could you open a new issue for me and I will debug it later, and of course any pull request to fix this is also appreciated!
