### ISSUE TITLE
Can not 'import' or 'require' in ES6

### ISSUE THREAD

**Issue by isLooge** [rrweb-io/rrweb-player#11]
when I use **npm install --save rrweb-player** add to my React project, use **import rrwebPlayer from 'rrweb-player'** in my component, **console.log(rrwebPlayer)** print out its reference src，eg: **/static/media/index.4025ef79.mjs**,How do I use it？

**Comment by Yuyz0112** [comment]
I have a simple project created by `create-react-app` and use typescript: https://github.com/Yuyz0112/project-r/blob/master/src/components/Player.tsx#L2

And `import rrwebPlayer from 'rrweb-player';` works for me. Is this a bundler thing?

**Comment by isLooge** [comment]
> I have a simple project created by `create-react-app` and use typescript: https://github.com/Yuyz0112/project-r/blob/master/src/components/Player.tsx#L2
> 
> And `import rrwebPlayer from 'rrweb-player';` works for me. Is this a bundler thing?

#### Can works the page?

**Comment by isLooge** [comment]
I don't use typescript.
Here's how I use it：
```
// ...
import rrwebPlayer from 'rrweb-player';
// ...
componentDidMount = () => {
        console.log(rrwebPlayer);
        const { id = '' } = this.state;
        rumsRequest({ url: RRWEB_API.POST_GETBACKTRACKINGPARAM, data: { id } }).then(res => {
            let jsonResult = res.data;
            new rrwebPlayer({
                target: document.getElementById('rrwebReplayer'),
                data: {
                    events: jsonResult.param,
                    autoPlay: false
                },
            });
        });
    };
// ...
```
![image](https://user-images.githubusercontent.com/26812736/68839391-997ebf80-06fb-11ea-93f7-ff01e4ba11c2.png)

**Comment by Yuyz0112** [comment]
@isLooge I see. Looks like webpack does not respect the es-module file with `.mjs` extension by default.

I have just released `0.4.0` with a common-js bundle.

**Comment by isLooge** [comment]
@Yuyz0112 Thanks,I try it!

**Comment by isLooge** [comment]
@Yuyz0112 Hello，thinks for your help yesterday。I find it problem in my project，attributed to webpack no configuration **file-loader** for **.mjs** file.
I wish you can set export default main file is **.js**，because I think it is more widely used.
Hope this project gets better and better!

My English cooperation level is not good, write wrong place still please forgive me. ^_^_^

**Comment by Yuyz0112** [comment]
@isLooge yes, it now use a `.js` file as the main exporter https://github.com/rrweb-io/rrweb-player/blob/master/package.json#L30

**Comment by rtyshyk** [comment]
I tried version `0.7.0` and it does not work. I use `antd` afaik it is like `create-react-app`.  Would appreciate your help.

See usage example below. The error is the same 
![image](https://user-images.githubusercontent.com/1192326/70452143-4ce69400-1aaf-11ea-90a9-7a1129962aba.png)

```js
import React, { Component } from 'react';
import rrwebPlayer from 'rrweb-player';
// import 'rrweb-player/dist/style.css';
// import { Replayer } from 'rrweb';

class RecordingsPlayer extends Component {
  constructor(props) {
    super(props);
    this.playerRef = React.createRef();
  }

  componentDidMount() {
    const events = this.props.events.map((event) => {
      return {
        ...event,
        data: event.data,
        timestamp: new Date(event.timestamp).getTime(),
      };
    });

    // doesn't work
    new rrwebPlayer({
      target: this.playerRef.current, // customizable root element
      data: {
        events,
        autoPlay: false,
      },
    });

    // works
    // const replayer = new Replayer(events, { root: this.playerRef.current });
    // replayer.play();
  }

  render() {
    return <div ref={this.playerRef} />;
  }
}

export default RecordingsPlayer;
```

**Comment by Yuyz0112** [comment]
@rtyshyk What's your rrweb-player's version?

**Comment by rtyshyk** [comment]
@Yuyz0112  I was trying  0.4.0 as well as 0.3.17
