### ISSUE TITLE
rrweb-player controller not fetching any styles.

### ISSUE THREAD

**Issue by monikasaran293** [rrweb-io/rrweb-player#12]
I am trying to use rrweb-player in my react app, and the controllers are rendering without styles and also I am not able to change the size of the frame. Please help me out with any suggestions.

new rrwebPlayer({
       target: root,
       data: {
              events: events,
              autoPlay: true,
       },
})

**Comment by maximax123** [comment]
Do you use styled-components or something else?

**Comment by bian17888** [comment]
> I am trying to use rrweb-player in my react app, and the controllers are rendering without styles and also I am not able to change the size of the frame. Please help me out with any suggestions.
> 
> new rrwebPlayer({
> target: root,
> data: {
> events: events,
> autoPlay: true,
> },
> })

+1 for me!

**Comment by omairnabiel** [comment]
Did you find a solution to this. I'm having the same issue, styling is way too off. I'm using Vue fyi

**Comment by Yuyz0112** [comment]
Could you try `import 'rrweb-player/dist/style.css';` ?

**Comment by omairnabiel** [comment]
I ended up using [rrweb-player-vue](https://www.npmjs.com/package/@preflight-hq/rrweb-player-vue) for now, as I'm prototyping and testing things out and it worked out of the box.

**Comment by omairnabiel** [comment]
> import 'rrweb-player/dist/style.css'

This worked
