### ISSUE TITLE
How to destroy player?

### ISSUE THREAD

**Issue by bugwheels94** [rrweb-io/rrweb-player#18]
Hi, Suppose it is rendering on some react component and that components gets destroyed then how to cleanup the player?

I tried playerInstance.destroy() which kind of worked but the error came as shown below

```
Unhandled Runtime Error
TypeError: Cannot read property 'implementation' of null

Call Stack
buildNode
node_modules/rrweb-player/dist/index.mjs (1:11816)
buildNodeWithSN
node_modules/rrweb-player/dist/index.mjs (1:13360)
rebuild
node_modules/rrweb-player/dist/index.mjs (1:13736)
e.rebuildFullSnapshot
node_modules/rrweb-player/dist/index.mjs (1:24445)
n
node_modules/rrweb-player/dist/index.mjs (1:23265)
eval
node_modules/rrweb-player/dist/index.mjs (1:24134)
Object.doAction
node_modules/rrweb-player/dist/index.mjs (1:20889)```

**Comment by Yuyz0112** [comment]
I believe the player has been destroyed, and the error indicates that there are some events that were cast async.

A quick workaround is to try/catch the error and ignore it.

**Comment by bugwheels94** [comment]
The call stack has all of the function inside rrweb-player. How can I add try/catch on that? Should I edit the library's code? or window.onerror like global handler you meant?

**Comment by sibi-sharanyan** [comment]
`player.destroy()` doesn't seem to work now. Was it removed ?
How do we unmount the player ?

**Comment by Juice10** [comment]
This was fixed in a recent version of rrweb-player. And can be triggered by calling `.$destroy()`.
