### ISSUE TITLE
Update README.md to be more informative

### ISSUE THREAD

**Issue by slimlime** [rrweb-io/rrweb-player#19]
Currently appears to be standard boilerplate.

Demo examples can be run by installing node modules and using the npm scripts found in package.json~

**Comment by Yuyz0112** [comment]
Or maybe we can point it to the rrweb's guide in the README?

I'm preparing a new doc site for the whole rrweb project.

**Comment by Yuyz0112** [comment]
we will merge this repo into rrweb's monorepo
