### ISSUE TITLE
支持播放速度、showWarning、showDebug等的配置

### ISSUE THREAD

**Issue by jwentao** [rrweb-io/rrweb-player#21]
请问下为什么播放器不考虑支持播放速度、showWarning、showDebug等内容的配置呢？ 就像rrweb.Replayer那样，是建议我们自己利用rrweb.Replayer去实现一个player吗？

**Comment by Yuyz0112** [comment]
应该让 rrweb-player 支持所有 rrweb 的配置。

正在重写 rrweb-player。

**Comment by Yuyz0112** [comment]
Please see
https://github.com/rrweb-io/rrweb-player/pull/26
