### ISSUE TITLE
是否可以在播放时设置某些元素变为隐私状态？

### ISSUE THREAD

**Issue by yaakua** [rrweb-io/rrweb-player#24]
看rrweb介绍，在录制的时候可以通过增加class名字方式增加隐私字段。是否可以把这个功能移植到player当中？
业务背景：
1.录制时不需要隐藏
2.播放时根据用户的权限选择性的给予不同的人员不同的元素查看权限。

所以需要有在播放时去修改这些元素

**Comment by Yuyz0112** [comment]
@yaakua 

replay 的时候 `playerConfig` 也可以设置 `blockClass`，所以可以在播放的时候根据不同的人员传入不同的 blockClass。还可以设置 `insertStyleRules`，用来向 replayer 内部插入 CSS 样式。

**Comment by Yuyz0112** [comment]
可能是 rrweb-player 没有把这个配置透传出来

**Comment by yaakua** [comment]
> 可能是 rrweb-player 没有把这个配置透传出来

什么时候有这个功能可以透传出来？我这边看源码没太看明白，代码像VUE，但又感觉不是VUE。

**Comment by wangkai0717** [comment]
希望rrweb-player 能透传一下blockClass

**Comment by Yuyz0112** [comment]
最新的版本应该已经透传了所有配置
