### ISSUE TITLE
播放的时候会报错，原因是在给nodetype是3的node添加属性或者addchild

### ISSUE THREAD

**Issue by zhuhaoming1** [rrweb-io/rrweb-player#25]
你好，我在播放的时候发现一些问题。
原因是在给nodetype为3的node setAttribute或者addchild。
Node with id 'xxx' not found in
想知道什么原因会造成这些问题。请大佬指点，谢谢！

**Comment by Yuyz0112** [comment]
可以提供 events 用于 debug 吗？
