### ISSUE TITLE
Any method to reset the events?

### ISSUE THREAD

**Issue by andyyi** [rrweb-io/rrweb-player#28]
Hey, I have a list which would load the data via ajas request call based on the date range. When I change the date range and i would get the new data, then how can I play the different events based on the existing palyer on DOM? Looks that there is NO some method like "setEvents". Thanks.

**Comment by Yuyz0112** [comment]
Currently, you can destroy the player and use a new one. But I think the reset method is a good suggestion.

**Comment by Yuyz0112** [comment]
`replayer.$destroy()`

@daly2211

**Comment by daly2211** [comment]
thank you

**Comment by sibi-sharanyan** [comment]
Was the destroy() method removed?
It isn't working right now.

**Comment by Juice10** [comment]
> Was the destroy() method removed?
> It isn't working right now.

For the svelte based rrweb-player (this repo) it was renamed to `.$destroy()` (note the `$` in front of `destroy`)
