### ISSUE TITLE
能控制回放区域的尺寸吗

### ISSUE THREAD

**Issue by mrxiongmao** [rrweb-io/rrweb-player#29]
比如说我回放区域设置宽高为 800*400 ，我录制的数据能自动缩放在这个区域内完整展示吗

**Comment by Yuyz0112** [comment]
可以

```js
      const player = new rrwebPlayer({
        target: playerDomRef.current,
        props: {
          events,
          width: 800,
          height: 400,
        },
      });
```

**Comment by mrxiongmao** [comment]
const replayer = new rrwebPlayer({
    target: document.getElementById('replay-zone')
    props:{
         playerData,
         width: 800,
         height: 400,
    }
})
replayer.play()

报错 replayer need at least 2 events
是我哪儿用错了吗？
