### ISSUE TITLE
rrwebReplay 回放问题

### ISSUE THREAD

**Issue by mrxiongmao** [rrweb-io/rrweb-player#30]
代码如下：
let speed = 1
const playerData = [...]   // 已录制好的数据
const replayer = new rrwebReplay.Replay(playerData,{
   root:document.getElementById('replay-zone'),
  data{
     autoPlay:true
   },
  speed
})
replayer.play()

大佬，我想让该回放数据固定在  800*400的区域中显示，不管录制的数据的宽高是多少，等比缩放在这个区域内展示
该怎么做？

**Comment by Yuyz0112** [comment]
@mrxiongmao 
https://github.com/rrweb-io/rrweb-player/issues/29#issuecomment-678901468

这个设置 width 和 height 的方式不起作用吗？

**Comment by mrxiongmao** [comment]
是啊，没有作用

**Comment by Yuyz0112** [comment]
@mrxiongmao 可以发一下对应的代码和不生效的截图吗？

**Comment by mrxiongmao** [comment]
代码如下，（截图发不了，开发用的电脑做了外网控制连不上github，反正就是我设置了宽高，但是实际效果并没有作用）
const playerData = this.events   // 回放数据
const replayer = new rrwebPlay({
 target:document.getElementById('replay-zone'),
 props:{
    playerData,
    width:500,
    height:300
 },
 data:{
   events:playerData
}
 spped
})

![image](https://user-images.githubusercontent.com/12285766/91027888-41340100-e62f-11ea-92b9-6848b6eb55ca.png)

**Comment by Yuyz0112** [comment]
props 和 data 的作用是一样的，传一个就可以，传两个不会同时生效。

0.5+ 的版本使用 props，0.5- 的版本需要使用 data。

**Comment by mrxiongmao** [comment]
ok，可以了~ 谢谢大佬
