### ISSUE TITLE
倍数播放无效

### ISSUE THREAD

**Issue by lwadsy** [rrweb-io/rrweb-player#33]
倍数播放无效

**Comment by Yuyz0112** [comment]
怎么传入的配置呢？还是从 UI 操作无效？

**Comment by lwadsy** [comment]
从 UI 直接操作，用的mater分支代码

**Comment by lwadsy** [comment]
另外使用最新的版的播放器会出现权限问题，之前旧版的是没有问题的：
Blocked script execution in '<URL>' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.

<img width="719" alt="截屏2020-09-06 下午1 13 58" src="https://user-images.githubusercontent.com/17978301/92318737-40459b00-f043-11ea-96a4-082ad6d3a4aa.png">

**Comment by Yuyz0112** [comment]
@lwadsy 

sandbox 的提示是符合预期的，各个版本上都是有 sandbox 的实现避免安全问题，可能是因为源网站有所变化，让你触发了这个问题。

在 master 上是你本地 build 的吗？那可能需要检查一下：
1. node_modules 是否足够新
2. 最新的 release 版本（npm 或 CDN）上是否有这个问题

我在 master 分支上好像没有遇到问题

**Comment by lwadsy** [comment]
使用events.js 是没有问题的，使用之前录制的数据会出现这种情况

**Comment by Yuyz0112** [comment]
可以提供会出现问题的数据用于 debug 吗？

**Comment by Yuanfang-fe** [comment]
> 可以提供会出现问题的数据用于 debug 吗？

我这边master同样问题，setConfig({speed})不生效，rrweb那边master试了下也是不生效，但直接设置是没问题的，比如这样`let replayer = new Replayer(this.events, {
            root: this.$refs.replayContainer,
            skipInactive: false,
            speed: 1,
          })`

**Comment by Yuanfang-fe** [comment]
> 在本地build的，使用events.js 是没有问题的，使用之前录制的数据会出现这种情况

我本地修改rrweb中setConfig的代码后，重新编译后speed设置生效。
![image](https://user-images.githubusercontent.com/11530201/92459072-cc4cf380-f1f8-11ea-8a53-bea70c2973e9.png)

**Comment by lwadsy** [comment]
> > 在本地build的，使用events.js 是没有问题的，使用之前录制的数据会出现这种情况
> 
> 我本地修改rrweb中setConfig的代码后，重新编译后speed设置生效。
> ![image](https://user-images.githubusercontent.com/11530201/92459072-cc4cf380-f1f8-11ea-8a53-bea70c2973e9.png)

我试了一下还是不行，麻烦问一下rrweb和rrweb-play使用的什么版本？

**Comment by lwadsy** [comment]
> 可以提供会出现问题的数据用于 debug 吗？

**Comment by Yuanfang-fe** [comment]
> > > 在本地build的，使用events.js 是没有问题的，使用之前录制的数据会出现这种情况
> > 
> > 
> > 我本地修改rrweb中setConfig的代码后，重新编译后speed设置生效。
> > ![image](https://user-images.githubusercontent.com/11530201/92459072-cc4cf380-f1f8-11ea-8a53-bea70c2973e9.png)
> 
> 我试了一下还是不行，麻烦问一下rrweb和rrweb-play使用的什么版本？

0.91

**Comment by Yuyz0112** [comment]
已修复，感谢反馈
