### ISSUE TITLE
rrwebPlayer的全屏问题

### ISSUE THREAD

**Issue by mrxiongmao** [rrweb-io/rrweb-player#34]
大佬，我用rrwebPlayer全屏功能好像有问题，如图：
正常情况：
![image](https://user-images.githubusercontent.com/12285766/92460088-1d111c00-f1fa-11ea-9309-a8cc457680bd.png)
全屏状态下：
![image](https://user-images.githubusercontent.com/12285766/92460118-28fcde00-f1fa-11ea-84e0-438b3011466d.png)

该怎么处理能正常显示？
另外：倍数播放那块有什么办法可以只保留1x的按钮吗

**Comment by Juice10** [comment]
This could be due to a number of issues that where fixed. Or this is due to an external stylesheet that isn't allowed to be loaded due to CORS. Could you please create an issue on https://github.com/rrweb-io/rrweb and provide the events JSON you are using so we can debug this issue?
