### ISSUE TITLE
是否有提供接口生成本地的视频文件？谢谢

### ISSUE THREAD

**Issue by Finebme** [rrweb-io/rrweb-player#35]

**Comment by Yuanfang-fe** [comment]
> _No description provided._

https://github.com/tungs/timecut 可用这个生成

**Comment by Finebme** [comment]
> > _No description provided._
> 
> https://github.com/tungs/timecut 可用这个生成

Thank you so much : )

**Comment by Finebme** [comment]
https://github.com/tungs/timecut/issues/34#issuecomment-683515927
你好：）
我遇到了如上引用 timecut库的相同issue，timecut会往视频中插入自己的js逻辑，而rrwer-replay又是沙盒中运行的，不知道是否有调和的可能性？

**Comment by Yuanfang-fe** [comment]
![image](https://user-images.githubusercontent.com/11530201/93663563-8830dd00-fa9b-11ea-9cd3-194afd1b8ca5.png)
UNSAFE_replayCanvas 会在iframe 的sandbox属性上增加allow-scripts属性，即可运行js。

**Comment by Yuyz0112** [comment]
我来提供一个类似 timecut 的工具做这件事情吧，timecut 注入的 JS 逻辑对于 rrweb 转视频来说应该不是必要的。

**Comment by Yuyz0112** [comment]
https://github.com/rrweb-io/rrvideo

**Comment by Finebme** [comment]
Thanks!
