### ISSUE TITLE
回放白页面

### ISSUE THREAD

**Issue by lwadsy** [rrweb-io/rrweb-player#37]
[test1的副本.txt](https://github.com/rrweb-io/rrweb-player/files/5200984/test1.txt)
<img width="808" alt="截屏2020-09-10 下午6 25 14" src="https://user-images.githubusercontent.com/17978301/92717576-02be7600-f393-11ea-9f0c-6945e0c661d1.png">

**Comment by Yuyz0112** [comment]
看起来不是完整的 events，缺少了全量快照的数据。可以看看录制的 event 是否都被正确存储了。
