### ISSUE TITLE
浏览器等待状态

### ISSUE THREAD

**Issue by lwadsy** [rrweb-io/rrweb-player#39]
初始化rrwebPlayer后，将autoPlay设置为false后，浏览器一直处于等待状态，这个是否可以设置不处于等待状态？
    const component = new rrwebPlayer({
      target: document.body,
      data: {
        events,
        skipInactive: true,
        showDebug: true,
        showWarning: true,
        autoPlay: false,
      },
    });
![WechatIMG268](https://user-images.githubusercontent.com/17978301/93289738-af747980-f811-11ea-95c7-957f1ec5523c.png)

**Comment by Juice10** [comment]
This seems like a bug, could you please open an issue on https://github.com/rrweb-io/rrweb and provide a sample of your events.json so we can look into it.
Could you also provide a snapshot of your browser's DevTools network tab. It looks like it may have an issue loading some resources.
