### ISSUE TITLE
JS Error while replaying : "Uncaught DOMException: Failed to execute 'insertBefore' on 'Node'"

### ISSUE THREAD

**Issue by xavier-heysch** [rrweb-io/rrweb-player#4]
Hi,

I got a new issue while trying to replay a record.

Here the full error I got : 

`Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.`

I'm putting in attachement the json that contains everything that has been recorded -> [events.json.txt](https://github.com/rrweb-io/rrweb-player/files/3117743/events.json.txt)

Any idea regarding this one?

**Comment by Yuyz0112** [comment]
Looks like a rrweb error, going to debug it.

**Comment by xavier-heysch** [comment]
Thanks @Yuyz0112.

Sometimes I have this error too :

`Uncaught DOMException: Failed to execute 'removeChild' on 'Node': This node type does not support this method`

Don't know if it's related.

**Comment by Yuyz0112** [comment]
@xavier-heysch provide some events can reproduce the second one will be helpful.

**Comment by xavier-heysch** [comment]
@Yuyz0112 Sorry I don't have these events anymore. I will try to reproduce it and keep you informed.

**Comment by Yuyz0112** [comment]
@xavier-heysch 

https://github.com/rrweb-io/rrweb/commit/6d3b9c2345713ab0cb9c78da24a9959bb6e22c3a
rrweb has an important upgrade which passed this site's test:) You can have a try when it was released.

**Comment by xavier-heysch** [comment]
@Yuyz0112 Thanks for you feedback ! I will try this :)
