### ISSUE TITLE
回放时，录制页面中的滚动条可以被拖动

### ISSUE THREAD

**Issue by zjsen668** [rrweb-io/rrweb-player#42]
页面中有滚动条的，在回放时滚动条可以被拖动，有什么办法可以阻止播放时影响录制页面内的形式？
附件是可以重现的events文件
[events.zip](https://github.com/rrweb-io/rrweb-player/files/5272873/events.zip)

**Comment by Yuyz0112** [comment]
如果没有调用 `enableInteraction` 的话，回放应该默认是禁止点击、禁止滚动的。

**Comment by zjsen668** [comment]
> `enableInteraction`

我们只是对播放器的外观样式做了一些调整，没有调用这个方法，而且看解析出来的scroll属性确实也是no。
请问还可能是什么问题导致的呢？
![scroll](https://user-images.githubusercontent.com/16451999/94096303-55e5fd80-fe56-11ea-8c1c-c4aebb1a2c40.png)

**Comment by Juice10** [comment]
You can do this by calling `rrwebPlayer.getReplayer().enableInteract()`.

## Example
Run `$c.getReplayer().enableInteract()` in the your browsers DevTools Console on https://rrwebdebug.com/play/index.html?url=https%3A%2F%2Fjsonblob.com%2F8f412e6e-ea0d-11eb-bba7-55ccb0a510b6&version=0.7.3 and you'll be able to scroll and interact with the form elements.
