### ISSUE TITLE
版本播放时，内容错位

### ISSUE THREAD

**Issue by silenwym** [rrweb-io/rrweb-player#43]
rrweb-player在升级0.6.1版本后，播放内容错位，同时播放的比例与实际不同；
0.4.6版本无此问题，但0.4.6版本存在其他问题，所以现在卡住了。。。该如何处理呢
[events.json.txt](https://github.com/rrweb-io/rrweb-player/files/5282584/events.json.txt)

**Comment by Yuyz0112** [comment]
![Uploading Peek 2020-09-25 21-54.gif…]()
我本地测试的结果，哪部分错位？

**Comment by silenwym** [comment]
> ![窥视2020-09-25 21-54](https://user-images.githubusercontent.com/13651389/94275718-e406d480-ff79-11ea-863e-721624539ef4.gif)
> 
> 我本地测试的结果，哪部分错位？

帮忙看下这个json，里面childNodes  id为1729的没有展示出来，这个是什么原因呢
[1601183301888.json.txt](https://github.com/rrweb-io/rrweb-player/files/5287851/1601183301888.json.txt)
