### ISSUE TITLE
事件重复是否影响播放呢？

### ISSUE THREAD

**Issue by Jupiter-sxc** [rrweb-io/rrweb-player#47]
前端因为某些不可控原因发送给后台的事件event多发了一次，导致事件重复了，是否影响播放呢？测试是可以正常播放，看源码好像是排除掉了相同时间点的事件，但是不太确定这个会有什么潜在的影响。

**Comment by Yuyz0112** [comment]
有影响，如果发送的事件内容在回放时不是幂等的，例如 DOM 变化的事件，那可能导致回放失败

**Comment by Jupiter-sxc** [comment]
就是相同的事件存了两次呢，
