### ISSUE TITLE
TypeError: null is not an object (evaluating 'this.iframe.contentDocument.querySelectorAll')

### ISSUE THREAD

**Issue by billyvg** [rrweb-io/rrweb-player#48]
This seems to be throwing errors for us, here's the stack trace:

![image](https://user-images.githubusercontent.com/79684/99834115-ef105800-2b17-11eb-9f4a-1929e9c1fd33.png)

**Comment by Juice10** [comment]
Could you please re-open a ticket on https://github.com/rrweb-io/rrweb containing a json file of your events?
