### ISSUE TITLE
TypeError: Cannot read property 'implementation' of null

### ISSUE THREAD

**Issue by billyvg** [rrweb-io/rrweb-player#49]
Sorry, this is just the minified stacktrace:

![image](https://user-images.githubusercontent.com/79684/99834184-08190900-2b18-11eb-8caf-6c985b93d53d.png)

**Comment by Yuyz0112** [comment]
Hi @billyvg , is it possible to upload the events for debugging?

**Comment by Juice10** [comment]
Should be fixed in a recent version of rrweb(player).
