### ISSUE TITLE
Not able to run the player

### ISSUE THREAD

**Issue by KranthiGajula** [rrweb-io/rrweb-player#5]
I have used rrweb to capture certain events and exported them as a json file. 
I have 2 questions.
1) I am not able to run the player. I have downloaded the project from git and performed the steps mentioned in the readme. But I see a hello world text. I am not even sure I am doing it right. 
2) I want to use the json file as an input to the player.Is it possible?

**Comment by Yuyz0112** [comment]
@KranthiGajula sorry for the late.
Have you seen the [guide](https://github.com/rrweb-io/rrweb/blob/master/guide.md) in the main repo? The README in this repo is not updated and I'm sorry for that.

**Comment by KranthiGajula** [comment]
Thank You. I will read the 'ReadMe' in the main repo.

**Comment by Yuyz0112** [comment]
Closing due to no update.

**Comment by KranthiGajula** [comment]
Apologies. I should have responded earlier!
Following the document from another link has helped us and we were able to successfully integrate.

Thank you.
