### ISSUE TITLE
TypeError: Cannot read property 'createComment' of null

### ISSUE THREAD

**Issue by billyvg** [rrweb-io/rrweb-player#51]
This might be related to #50 and #49 

![image](https://user-images.githubusercontent.com/79684/99834619-4d3d3b00-2b18-11eb-9c14-7d5901448edf.png)

Some other similar exceptions:

![image](https://user-images.githubusercontent.com/79684/99834723-7d84d980-2b18-11eb-87dc-632a41d5fded.png)
![image](https://user-images.githubusercontent.com/79684/99834741-837aba80-2b18-11eb-80dc-fa3403329021.png)

**Comment by Juice10** [comment]
Should be fixed in a recent version of rrweb(player).
