### ISSUE TITLE
Support for liveMode

### ISSUE THREAD

**Issue by flomllr** [rrweb-io/rrweb-player#52]
Is it currently possible to have a `liveMode` with `rrwebPlayer` as described here: https://github.com/rrweb-io/rrweb/blob/master/docs/recipes/live-mode.md?

**Comment by Juice10** [comment]
Support for live mode is now baked in.
Here is an example of how you could use it:

```js
const player = new rrwebPlayer({
  target: document.body, // customizable root element
  props: {
    liveMode: true, // set the player to expect added events
    events: []
  },
});
player.addEvent(event) // this is how you add events to the player.
```
