### ISSUE TITLE
Caton died playing back the PDF. But with the playback in rrweb, there is no problem

### ISSUE THREAD

**Issue by moyishen** [rrweb-io/rrweb-player#56]
Hello: the same file with the progress of playback PDF when the card died. Here's how
new rrwebPlayer({
  target: document.body, /
  props: {
    events,
  },
});  It's going to be 7 to 8 seconds. It's going to be stuck. It's not responding.

But with the playback in rrweb, there is no problem.
const replayer = new rrweb.Replayer(events);
 replayer.play();  Can complete playback without jamming

**Comment by Juice10** [comment]
This sounds like you where using the latest version of rrweb at the time, and rrweb-player wasn't updated yet to use that version. This should be fixed now.

If not please re-open an issue containing your recorded events.json
