### ISSUE TITLE
How to unpack in rrwebPlayer

### ISSUE THREAD

**Issue by vincenzocasu** [rrweb-io/rrweb-player#57]
`new rrwebPlayer({
    target: document.body, // customizable root element
    props: {
      events,
      unpackFn: rrweb.unpack,
    },
  });`

This code not working... rrweb.unpack was not defined...

How can i unpack data in rrwebPlayer object?

**Comment by Wilson-hu** [comment]
同问～

**Comment by Juice10** [comment]
Please use import rrweb-all instead of rrweb. This will contain the unpacker. Example of rrweb-all version: https://cdn.jsdelivr.net/npm/rrweb@1.0.2/lib/rrweb-all.min.js
