### ISSUE TITLE
Uncaught DOMException: Failed to execute 'appendChild' on 'Node'

### ISSUE THREAD

**Issue by sumbatx15** [rrweb-io/rrweb-player#60]
Hi guys, love your work <3
I get an error when trying to replay 
**Uncaught DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.**
I don't really know why, but here are the events 
https://jsonblob.com/854837e1-7445-11eb-a6ca-357ae5633362
I tried with the latest release **rrweb-player 0.7.0**, and I'm still getting the same error

**Comment by Juice10** [comment]
Thanks for your submitting your issue!

This should be fixed when you do a recording with the latest version of rrweb (1.0 and above).

These events don't crash rrweb-player in version 0.7.3. Example: https://rrwebdebug.com/play/index.html?url=https%3A%2F%2Fjsonblob.com%2Fapi%2FjsonBlob%2F854837e1-7445-11eb-a6ca-357ae5633362&version=0.7.3 
But its does still show a broken recording.
