### ISSUE TITLE
How load async events into rrwebPlayer instance

### ISSUE THREAD

**Issue by vincenzocasu** [rrweb-io/rrweb-player#62]
Hi, is there a way to load events by ajax requests queue into rrwebPlayer instance?

At moment i have this code that load all the events in one shot... but for big json files the page load is too big...

```
const data = [{ events: <?php echo $json; ?> }];

function player(data){

  const events = data.reduce((prev, cur) => prev.concat(cur.events), []);

  new rrwebPlayer({
    target: document.body,
    props: {
      events
    },
  });

}

player(data);
```

Where $json is fetched by a php file_get_contents function

In the receipe guide i've found this code:
```
const replayer = new rrweb.Replayer(events)

for (const newEvent of newEvents) {
  replayer.addEvent(newEvent)
}
```

But I really don't know how inject into rrwebPlayer events dinamically...

Can someone helps me?

**Comment by vincenzocasu** [comment]
Analyzing the code I saw that an addEvent method is made available
So I changed the code like this and it works, but it doesn't update the total recording time ... where am I wrong?

The events are loaded correctly but the player's time not update ... and remain setted to 30seconds, So time stops at 30 seconds but the video continues to the end ... 

Can anyone give me a tip please?

```
const data = [{ events: <?php echo $json; ?> }];
const data2 =  [{ events: <?php echo $json2; ?> }];
let myPlayer = null;

function player(data){

  const events = data.reduce((prev, cur) => prev.concat(cur.events), []);

  myPlayer = new rrwebPlayer({
    target: document.body, // customizable root element
    props: {
      events // 30 seconds of registration
    },
  });

  setTimeout(function(){
    // simulate load new events
    const events2 = data2.reduce((prev, cur) => prev.concat(cur.events), []);
    for (const event of events2) {
      myPlayer.addEvent(event); // the events are loaded correctly but the player's time not update ... and remain setted to 30seconds, So time stops at 30 seconds but the video continues to the end ...
    }

  }, 2500);

}

player(data);
```

**Comment by Yuyz0112** [comment]
Yes, `addEvent` is for this usage. The metadata has not been updated maybe a bug.

**Comment by vincenzocasu** [comment]
@Yuyz0112 Thanks for your reply! 

Is there a way or s method to force meta update programmatically?

**Comment by vincenzocasu** [comment]
Hi @Yuyz0112  how are you? Have you some news about metadata update after new events are dinamically loaded?

**Comment by Juice10** [comment]
AFAIK addEvent doesn't work if you don't supply `liveMode: true`.

Example:

```js
const data = [{ events: <?php echo $json; ?> }];
const data2 =  [{ events: <?php echo $json2; ?> }];
let myPlayer = null;

function player(data){

  const events = data.reduce((prev, cur) => prev.concat(cur.events), []);

  myPlayer = new rrwebPlayer({
    target: document.body, // customizable root element
    props: {
      liveMode: true, // set the player to expect added events
      events // 30 seconds of registration
    },
  });

  setTimeout(function(){
    // simulate load new events
    const events2 = data2.reduce((prev, cur) => prev.concat(cur.events), []);
    for (const event of events2) {
      // the events are loaded correctly but the player's time not update ... 
      //and remain setted to 30seconds, So time stops at 30 seconds but the video continues to the end ...
      myPlayer.addEvent(event);
    }

  }, 2500);

}

player(data);
```

I'm closing this issue as we are migrating this repo to https://github.com/rrweb-io/rrweb. Could you see if this works for you?
