### ISSUE TITLE
insertStyleRules is not working as expected.

### ISSUE THREAD

**Issue by sibi-sharanyan** [rrweb-io/rrweb-player#65]
I'm trying to insert a rule to change the cursor styles. But the CSS is not getting applied. Am I doing something wrong here?
![image](https://user-images.githubusercontent.com/41921916/118513052-f32cd380-b750-11eb-8100-86a3d19d8e1f.png)

**Comment by Juice10** [comment]
`insertStyleRules` injects rules into the replay's iframe. The cursor (`.replayer-mouse`) lives outside the iframe. You can add these rules to your regular css files and they will work.
