### ISSUE TITLE
blockClass is not actually blocking the element

### ISSUE THREAD

**Issue by sibi-sharanyan** [rrweb-io/rrweb-player#67]
The DOM nodes with the blockClass specified are not being blocked. Instead, they are just getting a grey background. 
![image](https://user-images.githubusercontent.com/41921916/118673437-a14e8100-b816-11eb-8dc7-200034680eb2.png)

**Comment by Juice10** [comment]
This is a problem that happens at recording time. Could you create an issue on the [rrweb repo](https://github.com/rrweb-io/rrweb/issues/new) and supply your recorded events so we can reproduce this?
