### ISSUE TITLE
有支持canvas回放的计划吗？

### ISSUE THREAD

**Issue by Wilson-hu** [rrweb-io/rrweb-player#68]
同标题，rrweb那边现在支持录制canvas和回放，播放器这边可以支持一下么

**Comment by FeSeason** [comment]
![image](https://user-images.githubusercontent.com/12840843/119599575-dad74b80-be17-11eb-9f20-74265fb6c0cb.png)
@Wilson-hu

**Comment by lxf8808** [comment]
透传不起作用
