### ISSUE TITLE
TypeError: replayer.addEvent is not a function

### ISSUE THREAD

**Issue by hughfenghen** [rrweb-io/rrweb-player#7]
1. 我定位到异常发生在这一行代码：
https://github.com/rrweb-io/rrweb-player/blob/master/src/Player.html#L68
```js
addEvent(event) {
   // 单从语法上来看，应该会编译失败(replayer没有声明)，不知道为啥编译通过了。
   replayer.addEvent(event);
}
```

2. 在异常的行断点，在控制台打印`replayer`，确实没有`addEvent`方法。
![image](https://user-images.githubusercontent.com/3307051/59697068-c8ae0500-921f-11e9-9aa9-7cb108f36282.png)

3. 查看package.json `rrweb-player`依赖`rrweb@0.7.11`
而`rrweb@0.7.11`的commit记录已经包含`addEvent`方法了。
https://github.com/rrweb-io/rrweb/compare/0.7.11...master
![image](https://user-images.githubusercontent.com/3307051/59697948-4a526280-9221-11e9-9eab-8b17ab015115.png)

是不是构建rrweb的时候出了什么问题？

**Comment by hughfenghen** [comment]
clone `rrweb-player` 到本地，yarn link到`rrweb-player`，可以正常工作。

**Comment by Yuyz0112** [comment]
抱歉，rrweb 在这个 [commit](https://github.com/rrweb-io/rrweb/commit/2398f5c0b1646cf0c44c2e3cb4711f7024887a45) 里才加入了 addEvent 的方法，应该是我本地修改了引用之后没有改回来导致的错误。rrweb-player 不是用 Typescript 写的，所以不会检查出这个问题。

已经 release 了一个新版本解决这个问题。
