### ISSUE TITLE
Feature request: Inactive activity indicator on progressbar

### ISSUE THREAD

**Issue by omairnabiel** [rrweb-io/rrweb-player#77]
The `rrweb-player` shows an indicator for custom events but it would also be nice, to have some sort of indication of the inactive portion of the recording during playback. Recorded events can span to several minutes and it might be useful to know before hand where the inactive part is so it can be skipped `manually` as-well

**Comment by Juice10** [comment]
Moved this (back) to main repo due to monorepo merge: https://github.com/rrweb-io/rrweb-player/issues/77
