### ISSUE TITLE
Feature Required !! how to copy Text fields from the replay

### ISSUE THREAD

**Issue by codesiddhant** [rrweb-io/rrweb-player#79]
I wonder to know that how one can copy any of the text fields from the running replay to another
Html div on the same html page.

For example. If I record the screencast of online code editor and later it is possible to auto copy to these code to another div on the same page.
Using rrpalyer.

Please someone help me in this.

**Comment by Juice10** [comment]
You have access to the contents of the player's iframe via [`iframe.contentDocument`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement/contentDocument).
And you can do with those contents whatever you'd like, including copying contents of text fields to other divs.
