### ISSUE TITLE
Configuration skip inactive checkbox

### ISSUE THREAD

**Issue by mpstv** [rrweb-io/rrweb-player#8]
Hi everyone. Presently is not posible set skip inactive checkbox to false by default.
![image](https://user-images.githubusercontent.com/54762420/67861667-b62ecb00-fb31-11e9-8ced-f20f35776032.png)
I will try add this parameter.

**Comment by mpstv** [comment]
Please review #9

**Comment by perfectdaemon** [comment]
Hi everyone!

Is there any plans to release that improvement via npm?

**Comment by Yuyz0112** [comment]
@perfectdaemon Just released in 0.3.17, would you like to have a try?

**Comment by perfectdaemon** [comment]
We've tried 0.3.17. Parameter works perfect! Thanks @mpstv and @Yuyz0112
